-- PEGA ANIME POR NOME
SELECT * FROM    ANIME WHERE NOME LIKE "%:NOME%";
-- PEGA ANIMES POR ID DE EPISODIO 
SELECT * FROM    ANIME WHERE ID = (SELECT ANIME FROM EPISODIO WHERE ID = :ID);
-- PEGA ANIMES POR ID DO ANIME
SELECT * FROM    ANIME WHERE ID = :ID ORDER BY NOME;
-- PEGA TODOS OS ANIMES E SORTEIA POR NOME
SELECT * FROM    ANIME ORDER BY NOME;
-- PEGA ANIME POR CLASSIFICAÇÃO DUBLADO/LEGENDADO
SELECT * FROM 	 ANIME WHERE DUBLADO = :DUBLADO ORDER BY NOME;
-- PEGA SOMENTE OS NOMES DE ANIMES DO SITE
SELECT NOME FROM ANIME GROUP BY NOME ORDER BY NOME;

-- PEGA O ID DE UM CARTAO POR OUTROS DADOS BANCARIOS
SELECT ID FROM   CARTAO WHERE BANCO = :BANCO AND AGENCIA = :AGENCIA AND DIGITO_AGENCIA = :DIGITO_AGENCIA AND CONTA = :CONTA AND DIGITO_CONTA = :DIGITO_CONTA;
-- SELECT DE ID DE CARTAO POR ID DE USUARIO
SELECT ID FROM 	 CARTAO WHERE ID = (SELECT CARTAO FROM USUARIO WHERE ID = :ID);

-- PEGA ASSINATURA DO ANIME POR ID DO EPISODIO
SELECT * FROM    ASSINATURA WHERE ANIME = (SELECT ANIME FROM EPISODIO WHERE ID = :EPISODIO) AND USUARIO = :USUARIO;
-- PEGA ASSINTARUA DO ANIME POR ID DO ANIME
SELECT * FROM    ASSINATURA WHERE ANIME = :ANIME AND USUARIO = :USUARIO;
-- SELECIONA TODAS AS  ASSINATURAS POR ID DE USUARIO E ORDENA PELA DATA ASSINADA
SELECT * FROM 	 ASSINATURA WHERE USUARIO = :USUARIO ORDER BY DATA_ASSINADA DESC;

-- PEGA 4 EPISODIOS ORDENANDO PELA DATA DE LANCAMENTO
SELECT * FROM    EPISODIO ORDER BY DATA_LANCAMENTO DESC LIMIT 4;
-- PEGA EPISODIO POR ID
SELECT * FROM    EPISODIO WHERE ID = :ID;
-- PEGA EPISODIO TODOS OS EPISODIOS DE UM ANIME
SELECT * FROM    EPISODIO WHERE ANIME = :ANIME ORDER BY DATA_LANCAMENTO ASC;

-- PEGA TODAS AS INFORMAÇÕES DE UM USUARIO POR ID
SELECT * FROM    USUARIO WHERE ID = :ID;
-- PEGA TODAS AS INFORMAÇÕES DE UM USUARIO POR EMAIL E SENHA
SELECT * FROM    USUARIO WHERE EMAIL = :EMAIL AND SENHA = :SENHA;

-- ATUALIZA SENHA DO USUARIO
UPDATE 			 USUARIO SET SENHA = :SENHA WHERE ID = :ID;
-- ATUALIZA EMAIL DO USUARIO
UPDATE 			 USUARIO SET EMAIL = :EMAIL WHERE ID = :ID;

-- DELETAÇÃO DAS ASSINATURAS REFERENTES A UM ANIME
DELETE FROM 	 ASSINATURA WHERE ANIME = :ANIME;
-- DELETAÇÃO DOS EPISODIOS REFERENTES A UM ANIME
DELETE FROM 	 EPISODIO WHERE ANIME = :ANIME;
-- DELETE DE EPISODIO ESPECIFICO
DELETE FROM 	 EPISODIO WHERE ID = :ID;
-- DELETE DE ANIME POR ID
DELETE FROM 	 ANIME WHERE ID = :ID;
-- DELETE DE CARTAO POR ID
DELETE FROM 	 CARTAO WHERE ID = :ID;
-- DELETE DE ASSINATURA POR ID DE USUARIO
DELETE FROM 	 ASSINATURA WHERE USUARIO = :ID
-- DELETE DE CONTA DE USUARIO
DELETE FROM 	 USUARIO WHERE ID = :ID

-- INSERTS
INSERT INTO 	 ASSINATURA VALUES(:USUARIO, :ANIME, (SELECT VALOR_ASSINATURA FROM ANIME WHERE ID = :ANIME), DATE(NOW()));
INSERT INTO 	 ANIME (ID, NOME, DESCRICAO, DATA_LANCAMENTO, VALOR_ASSINATURA, CAMINHO_CAPA, DUBLADO) VALUES (:ID, :NOME, :DESCRICAO, :DATA_LANCAMENTO, :VALOR_ASSINATURA, :CAMINHO_CAPA, :DUBLADO);
INSERT INTO 	 CARTAO (BANCO, AGENCIA, DIGITO_AGENCIA, CONTA, DIGITO_CONTA) VALUES (:BANCO, :AGENCIA, :DIGITO_AGENCIA, :CONTA, :DIGITO_CONTA);
INSERT INTO 	 EPISODIO (ID, ANIME, NOME, DESCRICAO, CAMINHO_EPISODIO, DATA_LANCAMENTO) VALUES (:ID, :ANIME, :NOME, :DESCRICAO, :CAMINHO_EPISODIO, :DATA_LANCAMENTO);
INSERT INTO 	 USUARIO (ID, CPF, NOME, DATA_CADASTRO, CARTAO, EMAIL, SENHA, TIPO_USUARIO) VALUES (:ID, :CPF, :NOME, :DATA_CADASTRO, :CARTAO, :EMAIL, :SENHA, :TIPO_USUARIO);